<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- ========================================================== -->
  <!-- SPHERE IN PLACE OF GRIPPER POINT OF CONTACT                -->
  <!-- ========================================================== -->
  <xacro:macro name="gripper_dummy" params="prefix parent_link offset_xyz:='0 0 0' offset_rpy:='0 0 0'">

    <!-- ==================== PARAMETERS ==================== -->
    <xacro:property name="sphere_radius" value="0.01"/> <!-- 1 cm radius -->
    <xacro:property name="gripper_radius" value="0.05"/> <!-- 1 cm radius -->
    <xacro:property name="gripper_length" value="0.06"/> <!-- 1 cm radius -->
    <xacro:property name="sphere_color_orange" value="1.0 0.5 0.0 1.0"/> <!-- Orange RGBA -->
    <xacro:property name="sphere_color_green" value="0.3 1.0 0.3 1.0"/> <!-- green RGBA -->

    <!-- ==================== VISUAL SPHERE ==================== -->
    <link name="${prefix}_gripper_dummy">
      <visual>
      <origin xyz="0 0 0.06" rpy="${offset_rpy}"/>
        <geometry>
        
          <sphere radius="${sphere_radius}"/>
        </geometry>
        <material name="green">
          <color rgba="${sphere_color_green}"/>
        </material>
      </visual>
      <collision>
        <origin xyz="${offset_xyz}" rpy="${offset_rpy}"/>
        <geometry>
          <cylinder radius="${gripper_radius}" length="${gripper_length}"/>
        </geometry>
      </collision>
    </link>

    <!-- ==================== FIXED JOINT ==================== -->
    <joint name="${prefix}_gripper_dummy_joint" type="fixed">
      <parent link="${parent_link}"/>
      <child link="${prefix}_gripper_dummy"/>
      <origin xyz="0 0 ${gripper_length/2}" rpy="${offset_rpy}"/>
    </joint>

  </xacro:macro>

</robot>
